# Common emulator flags and locations
# Ensure the emulator and rom locations are for your system

ALOEVERA = "../../target/debug/aloevera"
X16_EMU = "../../../x16-emulator/x16emu"
X16_ROM = "../../../x16-rom/build/x16/rom.bin"
X16_EMU_FLAGS = -run -scale 4
#DEBUG = -debug 9000
